'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
export default function Home(){const[tasks,setTasks]=useState([]),[listening,setListening]=useState(false),[message,setMessage]=useState('Olá. Sou o Jarvis. Como posso ajudar?');
useEffect(()=>{loadTasks()},[]);
async function loadTasks(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const s=new Date();s.setHours(0,0,0,0);const e=new Date(s);e.setDate(e.getDate()+2);const{data}=await supabase.from('tasks').select('*').gte('due_at',s.toISOString()).lt('due_at',e.toISOString()).order('due_at');setTasks(data||[])}
function speak(t){setMessage(t);if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='pt-PT';speechSynthesis.speak(u)}}
function listen(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return speak('O reconhecimento de voz não é suportado neste navegador.');const r=new SR();r.lang='pt-PT';r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>speak('Não consegui perceber. Podes repetir?');r.onresult=e=>command(e.results[0][0].transcript);r.start()}
function command(text){const t=text.toLowerCase();if(t.includes('hoje')){const a=tasks.filter(x=>new Date(x.due_at).toDateString()===new Date().toDateString());speak(a.length?`Tens ${a.length} tarefa${a.length===1?'':'s'} para hoje.`:'Não tens tarefas para hoje.');}else if(t.includes('amanhã')){const d=new Date();d.setDate(d.getDate()+1);const a=tasks.filter(x=>new Date(x.due_at).toDateString()===d.toDateString());speak(a.length?`Tens ${a.length} tarefa${a.length===1?'':'s'} para amanhã.`:'Não tens tarefas para amanhã.')}else speak(`Ouvi: ${text}. A criação de tarefas por voz entra no próximo módulo.`)}
const d=new Date(),tm=new Date();tm.setDate(tm.getDate()+1);const today=tasks.filter(x=>new Date(x.due_at).toDateString()===d.toDateString()),tomorrow=tasks.filter(x=>new Date(x.due_at).toDateString()===tm.toDateString());return <main style={{minHeight:'100vh',background:'#f5f7fb',padding:32}}><div style={{maxWidth:1000,margin:'auto'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><small>ASSISTENTE PESSOAL</small><h1>Jarvis</h1></div><button onClick={listen} disabled={listening} style={{padding:'14px 20px',border:0,borderRadius:999,fontWeight:700}}>{listening?'🎙️ A ouvir...':'🎙️ Falar'}</button></header><section style={{background:'#fff',borderRadius:20,padding:24,margin:'20px 0'}}><small>ASSISTENTE</small><p style={{fontSize:22}}>{message}</p></section><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:18}}><Card title="📅 Hoje" tasks={today}/><Card title="📆 Amanhã" tasks={tomorrow}/><Card title="📰 Notícias" tasks={[]} news/></div></div></main>}
function Card({title,tasks,news}){return <section style={{background:'#fff',borderRadius:20,padding:22}}><h2>{title}</h2>{news?<p style={{opacity:.6}}>A ligação a notícias atualizadas será adicionada no próximo módulo.</p>:tasks.length?tasks.map(t=><div key={t.id} style={{padding:'12px 0',borderBottom:'1px solid #eee'}}><b>{t.title}</b><div style={{opacity:.55}}>{t.due_at&&new Date(t.due_at).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}</div></div>):<p style={{opacity:.55}}>Sem tarefas.</p>}</section>}
