'use client'
import {useEffect,useMemo,useRef,useState} from 'react'
import {createClient} from '@supabase/supabase-js'

type Task={id:string;title:string;due_at:string|null;completed:boolean}
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!)

export default function Home(){
 const [session,setSession]=useState<any>(null); const [tasks,setTasks]=useState<Task[]>([]); const [heard,setHeard]=useState(''); const [reply,setReply]=useState('Olá. Sou o Jarvis.'); const [listening,setListening]=useState(false); const [busy,setBusy]=useState(false); const [wakeEnabled,setWakeEnabled]=useState(false); const [news,setNews]=useState<string[]>([])
 const Recognition:any=useMemo(()=>typeof window!=='undefined' ? (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition : null,[])
 const wakeRef=useRef<any>(null); const commandRef=useRef<any>(null); const speakingRef=useRef(false); const wakeEnabledRef=useRef(false)
 useEffect(()=>{wakeEnabledRef.current=wakeEnabled},[wakeEnabled])
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe()},[])
 async function login(){const email=prompt('Email para entrar no Jarvis:'); if(!email)return; const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}}); alert(error?error.message:'Enviámos um link de acesso para o teu email.')}
 async function loadTasks(){if(!session)return; const {data}=await supabase.from('tasks').select('id,title,due_at,completed').order('due_at',{ascending:true}); if(data)setTasks(data)}
 useEffect(()=>{if(session){loadTasks(); setNews(['As notícias serão ligadas na próxima etapa.'])}},[session])
 function pickVoice(){const voices=speechSynthesis.getVoices(); const pt=voices.filter(v=>v.lang.toLowerCase().startsWith('pt-pt')); const preferred=['rui','duarte','jorge','joao','joão','ricardo','daniel','miguel','male','man']; return [...pt,...voices.filter(v=>v.lang.toLowerCase().startsWith('pt')),...voices].find(v=>preferred.some(x=>v.name.toLowerCase().includes(x))) || pt[0] || voices.find(v=>v.lang.toLowerCase().startsWith('pt'))}
 function stopRecognition(){try{wakeRef.current?.stop()}catch{} try{commandRef.current?.stop()}catch{} wakeRef.current=null; commandRef.current=null; setListening(false)}
 function speak(text:string){setReply(text); if(!('speechSynthesis' in window))return; stopRecognition(); speakingRef.current=true; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.lang='pt-PT'; u.rate=.88; u.pitch=.86; u.volume=1; const v=pickVoice(); if(v)u.voice=v; u.onend=()=>{speakingRef.current=false; if(wakeEnabledRef.current) startWake()}; u.onerror=()=>{speakingRef.current=false; if(wakeEnabledRef.current) startWake()}; speechSynthesis.speak(u)}
 async function command(text:string){const clean=text.trim(); if(!clean)return; setBusy(true); setHeard(clean); try{const r=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/jarvis-command`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({command:clean})}); const j=await r.json(); speak(j.spoken||j.error||'Não consegui processar o comando.'); await loadTasks()}catch{ speak('Houve um problema ao processar o comando.') }finally{setBusy(false)}}
 function startCommand(){if(!Recognition)return; stopRecognition(); const r=new Recognition(); commandRef.current=r; r.lang='pt-PT'; r.interimResults=false; r.continuous=false; r.onstart=()=>setListening(true); r.onresult=(e:any)=>command(e.results[0][0].transcript); r.onerror=()=>{setListening(false); if(wakeEnabledRef.current)speak('Não consegui ouvir-te.')}; r.onend=()=>{commandRef.current=null; setListening(false)}; r.start()}
 function startWake(){if(!Recognition||!wakeEnabledRef.current||speakingRef.current)return; try{wakeRef.current?.stop()}catch{} const r=new Recognition(); wakeRef.current=r; r.lang='pt-PT'; r.interimResults=true; r.continuous=true; r.onstart=()=>setListening(true); r.onresult=(e:any)=>{for(let i=e.resultIndex;i<e.results.length;i++){const text=String(e.results[i][0].transcript||'').trim(); const lower=text.toLowerCase(); const idx=lower.indexOf('jarvis'); if(idx>=0){const after=text.slice(idx+6).trim().replace(/^[,;:.-]+/,'').trim(); if(after){command(after)}else{speak('Sim?'); setTimeout(()=>{if(wakeEnabledRef.current&&!speakingRef.current)startCommand()},700)} return}}}; r.onerror=()=>{wakeRef.current=null; setListening(false); if(wakeEnabledRef.current&&!speakingRef.current)setTimeout(startWake,800)}; r.onend=()=>{wakeRef.current=null; setListening(false); if(wakeEnabledRef.current&&!speakingRef.current)setTimeout(startWake,350)}; try{r.start()}catch{setTimeout(startWake,800)}}
 function toggleWake(){if(!Recognition){speak('O teu navegador não suporta reconhecimento de voz contínuo. Usa Chrome ou Edge.');return} if(wakeEnabled){setWakeEnabled(false); wakeEnabledRef.current=false; stopRecognition(); speak('Modo Jarvis desligado.')}else{setWakeEnabled(true); wakeEnabledRef.current=true; speak('Estou atento. Diz Jarvis quando precisares de mim.')}}
 function listen(){if(!Recognition){speak('O teu navegador não suporta reconhecimento de voz. Usa Chrome ou Edge.');return} startCommand()}
 useEffect(()=>{const onVoices=()=>{}; speechSynthesis?.addEventListener?.('voiceschanged',onVoices); return()=>speechSynthesis?.removeEventListener?.('voiceschanged',onVoices)},[])
 const today=new Date(); const tomorrow=new Date(today); tomorrow.setDate(today.getDate()+1); function sameDay(a:string|null,b:Date){if(!a)return false;const d=new Date(a);return d.toDateString()===b.toDateString()}
 if(!session)return <main className="center"><div className="card login"><div className="orb">J</div><h1>JARVIS</h1><p>O teu assistente pessoal por voz.</p><button onClick={login}>Entrar no Jarvis</button></div></main>
 const todayTasks=tasks.filter(t=>sameDay(t.due_at,today)&&!t.completed), tomorrowTasks=tasks.filter(t=>sameDay(t.due_at,tomorrow)&&!t.completed)
 return <main><header><div><span className="eyebrow">ASSISTENTE PESSOAL</span><h1>JARVIS</h1></div><button className="ghost" onClick={()=>supabase.auth.signOut()}>Sair</button></header><section className="hero"><div className={`orb ${listening?'pulse':''}`}>J</div><div><h2>{listening?'Estou a ouvir…':busy?'A processar…':'Olá. Em que posso ajudar?'}</h2><p>{heard?`“${heard}”`:reply}</p></div><div className="voice-actions"><button className="mic" onClick={listen}>{listening?'■':'🎙️'}</button><button className={`wake ${wakeEnabled?'active':''}`} onClick={toggleWake}>{wakeEnabled?'● Jarvis ativo':'○ Ativar “Jarvis”'}</button></div></section><section className="grid"><div className="panel"><h3>Hoje</h3>{todayTasks.length?<ul>{todayTasks.map(t=><li key={t.id}>{t.title}<small>{t.due_at&&new Date(t.due_at).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}</small></li>)}</ul>:<p className="muted">Sem tarefas pendentes.</p>}</div><div className="panel"><h3>Amanhã</h3>{tomorrowTasks.length?<ul>{tomorrowTasks.map(t=><li key={t.id}>{t.title}<small>{t.due_at&&new Date(t.due_at).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}</small></li>)}</ul>:<p className="muted">Sem tarefas pendentes.</p>}</div></section><section className="panel news"><h3>Notícias</h3>{news.map((n,i)=><p key={i}>{n}</p>)}</section><div className="examples"><span>Experimenta dizer:</span><button onClick={()=>command('O que tenho para hoje?')}>“O que tenho para hoje?”</button><button onClick={()=>command('Adiciona uma reunião amanhã às 10 horas')}>“Adiciona uma reunião amanhã às 10”</button></div></main>
}
