'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '@supabase/supabase-js'

type Task={id:string;title:string;due_at:string|null;completed:boolean}
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!)

export default function Home(){
 const [session,setSession]=useState<any>(null); const [tasks,setTasks]=useState<Task[]>([]); const [heard,setHeard]=useState(''); const [reply,setReply]=useState('Olá. Sou o Jarvis.'); const [listening,setListening]=useState(false); const [busy,setBusy]=useState(false); const [news,setNews]=useState<string[]>([])
 const Recognition:any=useMemo(()=>typeof window!=='undefined' ? (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition : null,[])
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe()},[])
 async function login(){const email=prompt('Email para entrar no Jarvis:'); if(!email)return; const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}}); alert(error?error.message:'Enviámos um link de acesso para o teu email.')}
 async function loadTasks(){if(!session)return; const {data}=await supabase.from('tasks').select('id,title,due_at,completed').order('due_at',{ascending:true}); if(data)setTasks(data)}
 useEffect(()=>{if(session){loadTasks(); setNews(['As notícias serão ligadas na próxima etapa.'])}},[session])
 function speak(text:string){setReply(text); if('speechSynthesis' in window){speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.lang='pt-PT'; u.rate=.92; const v=speechSynthesis.getVoices().find(x=>x.lang.toLowerCase().startsWith('pt-pt')); if(v)u.voice=v; speechSynthesis.speak(u)}}
 async function command(text:string){setBusy(true); setHeard(text); try{const r=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/jarvis-command`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({command:text})}); const j=await r.json(); speak(j.spoken||j.error||'Não consegui processar o comando.'); await loadTasks()}finally{setBusy(false)}}
 function listen(){if(!Recognition){speak('O teu navegador não suporta reconhecimento de voz. Usa Chrome ou Edge.');return} const r=new Recognition(); r.lang='pt-PT'; r.interimResults=false; r.continuous=false; r.onstart=()=>setListening(true); r.onend=()=>setListening(false); r.onerror=()=>{setListening(false);speak('Não consegui ouvir-te. Tenta novamente.')}; r.onresult=(e:any)=>command(e.results[0][0].transcript); r.start()}
 const today=new Date(); const tomorrow=new Date(today); tomorrow.setDate(today.getDate()+1); function sameDay(a:string|null,b:Date){if(!a)return false;const d=new Date(a);return d.toDateString()===b.toDateString()}
 if(!session)return <main className="center"><div className="card login"><div className="orb">J</div><h1>JARVIS</h1><p>O teu assistente pessoal por voz.</p><button onClick={login}>Entrar no Jarvis</button></div></main>
 const todayTasks=tasks.filter(t=>sameDay(t.due_at,today)&&!t.completed), tomorrowTasks=tasks.filter(t=>sameDay(t.due_at,tomorrow)&&!t.completed)
 return <main><header><div><span className="eyebrow">ASSISTENTE PESSOAL</span><h1>JARVIS</h1></div><button className="ghost" onClick={()=>supabase.auth.signOut()}>Sair</button></header><section className="hero"><div className={`orb ${listening?'pulse':''}`}>J</div><div><h2>{listening?'Estou a ouvir…':busy?'A processar…':'Olá. Em que posso ajudar?'}</h2><p>{heard?`“${heard}”`:reply}</p></div><button className="mic" onClick={listen}>{listening?'■':'🎙️'}</button></section><section className="grid"><div className="panel"><h3>Hoje</h3>{todayTasks.length?<ul>{todayTasks.map(t=><li key={t.id}>{t.title}<small>{t.due_at&&new Date(t.due_at).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}</small></li>)}</ul>:<p className="muted">Sem tarefas pendentes.</p>}</div><div className="panel"><h3>Amanhã</h3>{tomorrowTasks.length?<ul>{tomorrowTasks.map(t=><li key={t.id}>{t.title}<small>{t.due_at&&new Date(t.due_at).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}</small></li>)}</ul>:<p className="muted">Sem tarefas pendentes.</p>}</div></section><section className="panel news"><h3>Notícias</h3>{news.map((n,i)=><p key={i}>{n}</p>)}</section><div className="examples"><span>Experimenta dizer:</span><button onClick={()=>command('O que tenho para hoje?')}>“O que tenho para hoje?”</button><button onClick={()=>command('Adiciona uma reunião amanhã às 10 horas')}>“Adiciona uma reunião amanhã às 10”</button></div></main>
}
